package model

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*BindMountMode bind mount mode

swagger:model BindMountMode
*/
type BindMountMode int32

// Validate validates this bind mount mode
func (m BindMountMode) Validate(formats strfmt.Registry) error {
	return nil
}
