package model

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*HealthCheckType health check type

swagger:model HealthCheckType
*/
type HealthCheckType string

// Validate validates this health check type
func (m HealthCheckType) Validate(formats strfmt.Registry) error {
	return nil
}
