package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*VolumeMount volume mount

swagger:model VolumeMount
*/
type VolumeMount struct {

	/* config
	 */
	Config string `json:"config,omitempty"`

	/* container path
	 */
	ContainerPath string `json:"container_path,omitempty"`

	/* driver
	 */
	Driver string `json:"driver,omitempty"`

	/* mode
	 */
	Mode BindMountMode `json:"mode,omitempty"`

	/* volume id
	 */
	VolumeID string `json:"volume_id,omitempty"`
}

// Validate validates this volume mount
func (m *VolumeMount) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
