package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*CancelTaskAccepted Cancel request accepted

swagger:response cancelTaskAccepted
*/
type CancelTaskAccepted struct {
}

// NewCancelTaskAccepted creates CancelTaskAccepted with default headers values
func NewCancelTaskAccepted() *CancelTaskAccepted {
	return &CancelTaskAccepted{}
}

// WriteResponse to the client
func (o *CancelTaskAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
}

/*CancelTaskNotFound Can't find staging task

swagger:response cancelTaskNotFound
*/
type CancelTaskNotFound struct {
}

// NewCancelTaskNotFound creates CancelTaskNotFound with default headers values
func NewCancelTaskNotFound() *CancelTaskNotFound {
	return &CancelTaskNotFound{}
}

// WriteResponse to the client
func (o *CancelTaskNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*CancelTaskServiceUnavailable Cloud Controller unavailable

swagger:response cancelTaskServiceUnavailable
*/
type CancelTaskServiceUnavailable struct {
}

// NewCancelTaskServiceUnavailable creates CancelTaskServiceUnavailable with default headers values
func NewCancelTaskServiceUnavailable() *CancelTaskServiceUnavailable {
	return &CancelTaskServiceUnavailable{}
}

// WriteResponse to the client
func (o *CancelTaskServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
