package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelTaskParams creates a new CancelTaskParams object
// with the default values initialized.
func NewCancelTaskParams() CancelTaskParams {
	var ()
	return CancelTaskParams{}
}

// CancelTaskParams contains all the bound params for the cancel task operation
// typically these are obtained from a http.Request
//
// swagger:parameters cancelTask
type CancelTaskParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	TaskGUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CancelTaskParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rTaskGUID, rhkTaskGUID, _ := route.Params.GetOK("task_guid")
	if err := o.bindTaskGUID(rTaskGUID, rhkTaskGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CancelTaskParams) bindTaskGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.TaskGUID = raw

	return nil
}
