package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cf-furnace/k8s-nsync/lib/model"
)

// NewDesireAppParams creates a new DesireAppParams object
// with the default values initialized.
func NewDesireAppParams() DesireAppParams {
	var ()
	return DesireAppParams{}
}

// DesireAppParams contains all the bound params for the desire app operation
// typically these are obtained from a http.Request
//
// swagger:parameters desireApp
type DesireAppParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: body
	*/
	DesireAppRequest *model.DesireAppRequestFromCC
	/*
	  Required: true
	  In: path
	*/
	ProcessGUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DesireAppParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body model.DesireAppRequestFromCC
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("desireAppRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("desireAppRequest", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.DesireAppRequest = &body
			}
		}

	} else {
		res = append(res, errors.Required("desireAppRequest", "body"))
	}

	rProcessGUID, rhkProcessGUID, _ := route.Params.GetOK("process_guid")
	if err := o.bindProcessGUID(rProcessGUID, rhkProcessGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DesireAppParams) bindProcessGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ProcessGUID = raw

	return nil
}
