package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DesireAppAccepted LRP request accepted

swagger:response desireAppAccepted
*/
type DesireAppAccepted struct {
}

// NewDesireAppAccepted creates DesireAppAccepted with default headers values
func NewDesireAppAccepted() *DesireAppAccepted {
	return &DesireAppAccepted{}
}

// WriteResponse to the client
func (o *DesireAppAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
}

/*DesireAppBadRequest JSON unmarshalling error or process-guid mismatch or bad request

swagger:response desireAppBadRequest
*/
type DesireAppBadRequest struct {
}

// NewDesireAppBadRequest creates DesireAppBadRequest with default headers values
func NewDesireAppBadRequest() *DesireAppBadRequest {
	return &DesireAppBadRequest{}
}

// WriteResponse to the client
func (o *DesireAppBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*DesireAppConflict Resource conflict

swagger:response desireAppConflict
*/
type DesireAppConflict struct {
}

// NewDesireAppConflict creates DesireAppConflict with default headers values
func NewDesireAppConflict() *DesireAppConflict {
	return &DesireAppConflict{}
}

// WriteResponse to the client
func (o *DesireAppConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}

/*DesireAppServiceUnavailable Cannot find/create desired LRP

swagger:response desireAppServiceUnavailable
*/
type DesireAppServiceUnavailable struct {
}

// NewDesireAppServiceUnavailable creates DesireAppServiceUnavailable with default headers values
func NewDesireAppServiceUnavailable() *DesireAppServiceUnavailable {
	return &DesireAppServiceUnavailable{}
}

// WriteResponse to the client
func (o *DesireAppServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
