package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/cf-furnace/k8s-nsync/lib/model"
)

// NewDesireTaskParams creates a new DesireTaskParams object
// with the default values initialized.
func NewDesireTaskParams() DesireTaskParams {
	var ()
	return DesireTaskParams{}
}

// DesireTaskParams contains all the bound params for the desire task operation
// typically these are obtained from a http.Request
//
// swagger:parameters desireTask
type DesireTaskParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: body
	*/
	TaskRequest *model.TaskRequestFromCC
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DesireTaskParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body model.TaskRequestFromCC
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("taskRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("taskRequest", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TaskRequest = &body
			}
		}

	} else {
		res = append(res, errors.Required("taskRequest", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
