package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewKillIndexParams creates a new KillIndexParams object
// with the default values initialized.
func NewKillIndexParams() KillIndexParams {
	var ()
	return KillIndexParams{}
}

// KillIndexParams contains all the bound params for the kill index operation
// typically these are obtained from a http.Request
//
// swagger:parameters killIndex
type KillIndexParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	Index string
	/*
	  Required: true
	  In: path
	*/
	ProcessGUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *KillIndexParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rIndex, rhkIndex, _ := route.Params.GetOK("index")
	if err := o.bindIndex(rIndex, rhkIndex, route.Formats); err != nil {
		res = append(res, err)
	}

	rProcessGUID, rhkProcessGUID, _ := route.Params.GetOK("process_guid")
	if err := o.bindProcessGUID(rProcessGUID, rhkProcessGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *KillIndexParams) bindIndex(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Index = raw

	return nil
}

func (o *KillIndexParams) bindProcessGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ProcessGUID = raw

	return nil
}
