package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*StopAppAccepted Request to stop app accepted

swagger:response stopAppAccepted
*/
type StopAppAccepted struct {
}

// NewStopAppAccepted creates StopAppAccepted with default headers values
func NewStopAppAccepted() *StopAppAccepted {
	return &StopAppAccepted{}
}

// WriteResponse to the client
func (o *StopAppAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
}

/*StopAppBadRequest Missing process guid

swagger:response stopAppBadRequest
*/
type StopAppBadRequest struct {
}

// NewStopAppBadRequest creates StopAppBadRequest with default headers values
func NewStopAppBadRequest() *StopAppBadRequest {
	return &StopAppBadRequest{}
}

// WriteResponse to the client
func (o *StopAppBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*StopAppNotFound Process not found

swagger:response stopAppNotFound
*/
type StopAppNotFound struct {
}

// NewStopAppNotFound creates StopAppNotFound with default headers values
func NewStopAppNotFound() *StopAppNotFound {
	return &StopAppNotFound{}
}

// WriteResponse to the client
func (o *StopAppNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*StopAppServiceUnavailable Service unavailable

swagger:response stopAppServiceUnavailable
*/
type StopAppServiceUnavailable struct {
}

// NewStopAppServiceUnavailable creates StopAppServiceUnavailable with default headers values
func NewStopAppServiceUnavailable() *StopAppServiceUnavailable {
	return &StopAppServiceUnavailable{}
}

// WriteResponse to the client
func (o *StopAppServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
